### ISSUE TITLE
Front-end improvements

### ISSUE THREAD

**Issue by M7PAX** [Lempac/Oxy#19]
**REWRITE PRETTY MUCH EVERYTHING!!!**

1. Turn all css to tailwindcss (there are websites which do it for you, like this one - [https://transform.tools/css-to-tailwind](url))
2. Start using daisy ui, there are components that make your job 10x easier - [https://daisyui.com/](url)
3. The websites design is meant to be top to bottom, sadly youre gonna have to remake the settings select side bar to a top bar
4. Please for gods sake dont add more css to existing components, the whole point is to leave them how they are
     4. 1. Remove all css from components when using them
     4. 2. _This is just a note_ - Use daisy ui over premade vue components 
5. Also just use the default laravel theme for now, we'll go through the actual theme later, just make the design for now

 _6. to be continued_

**no hate, just trying to make this easier for everyone**

_to see how far you are, comment the points that are done_

**Comment by Lempac** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Settings](https://trello.com/c/LzsnmODg/23-settings)

**Comment by 21DP3EFrei** [comment]
![Screenshot_20241011-200446~2](https://github.com/user-attachments/assets/b5638837-4125-4287-9c5e-79a72da7a94e)
